# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build KC HC library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://oss.sonatype.org/content/repositories/snapshots
        username: ${{ secrets.SONARTYPE_USER }}
        password: ${{ secrets.SONARTYPE_SEC }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=net.loobpack artifactId=kafka-connect-healthcheck-extension version=0.0.5
        assets: extension=jar
        filename: ./target/kafka-connect-healthcheck-extension-0.0.5-SNAPSHOT.jar
